### ISSUE TITLE
Les labels dans l'interface doivent avoir exactement le meme format

### ISSUE THREAD

**Issue by massimotisi** [CACAO2016/CACAO2016#16]
Des examples dans la version courante:
- Achats de Leclerc
- Achats de T1. Nestle
- stock de cacaode Lindt
- Fond deP2. Asie Amerique

**Comment by massimotisi** [comment]
@florianed, @jhtr, @AlexandreMarty, @MarcSuteau, @SofianeSalort et @lakac: vous etes censé vous mettre d'accord sur un format commun avant la v2.0

**Comment by massimotisi** [comment]
@florianed, @jhtr, @AlexandreMarty, @MarcSuteau, @SofianeSalort et @lakac: est-ce que vous avez choisi un format commun?

**Comment by massimotisi** [comment]
@florianed, @jhtr, @AlexandreMarty, @MarcSuteau, @SofianeSalort et @lakac: je ne vois pas de progres sur cet issue.

**Comment by jhtr** [comment]
Je propose que tout le monde utilise la convention qu'il y avait à la version 0.

>

**Comment by florianed** [comment]
Nous allons essayer d'en discuter, désolée du retard.

**Comment by massimotisi** [comment]
@auberield, @jhtr, @AlexandreMarty, @MarcSuteau, @SofianeSalort et @lakac: je ne vois pas de progres sur cet issue

**Comment by massimotisi** [comment]
@jhtr @AlexandreMARTY: vos groupes ont encore des labels dans l'ancien format (P1. ...)

**Comment by massimotisi** [comment]
@SofianeSalort: pouvez-vous mettre à jour le label de votre journal?

**Comment by SofianeSalort** [comment]
Je fais ça tout de suite

**Comment by massimotisi** [comment]
Je ferme cet issue et je vais rejecter toutes pull requests qui ne suivent pas le format choisi
