### ISSUE TITLE
Conversion code deprecated

### ISSUE THREAD

**Issue by massimotisi** [CACAO2016/CACAO2016#27]
Au moment de la release de la v0.2 les methodes deprecated seront supprimées. Il faut que les code soit changé pour n'utiliser plus ces methodes.

**Comment by massimotisi** [comment]
Bien sur c'est prioritaire de verifier immediatement que les methodes deprecated sont vraiment les methodes qu'il faut supprimer

**Comment by massimotisi** [comment]
Pour resumer: 
- jeudi je vais supprimer les methodes deprecated de ITransformateur, faites vos changements avant ça
- je peux deja supprimer les methodes deprecated de IDistributeur et IProducteur (svp ne les utilisez plus)

**Comment by massimotisi** [comment]
Pour etre encore plus precis les methodes deprecated de ITransformateur sont encore utilisés par le groupe 1 (@jhtr) et par des classes du package commun.

**Comment by massimotisi** [comment]
@florianed: vous appellez encore la methode ITransformateur.annonceQuantiteDemandee(IProducteur p) dans la methode Achat.setCacaoAchete(...).

**Comment by massimotisi** [comment]
@auberield: vous appellez encore la methode ITransformateur.annonceQuantiteDemandee(IProducteur p) dans la methode Achat.setCacaoAchete(...)

**Comment by florianed** [comment]
Bonjour, 

J'ai beau cherché, je ne trouve pas la fonction dont vous parlez. 
Existe-t-elle toujours?

**Comment by massimotisi** [comment]
@florianed, @auberield: desolé je me suis trompé de groupe. 

@AlexandreMARTY: vous appellez encore la methode ITransformateur.annonceQuantiteDemandee(IProducteur p) dans la methode Achat.setCacaoAchete(...). S'il vous plait corrigez.

**Comment by massimotisi** [comment]
@AlexandreMARTY: vous appellez encore la methode IProducteur.annonceQuantiteMiseEnVente(ITransformateurP p) dans la methode Achat.setCacaoAchete(...). S'il vous plait corrigez.

**Comment by massimotisi** [comment]
@AlexandreMARTY: aussi vous appellez encore la methode ITransformateur.annonceQuantiteDemandee(IProducteur p) dans la methode Achat.setCacaoAchete(...). S'il vous plait corrigez.

**Comment by AlexandreMARTY** [comment]
la classe Achat n'existe plus

**Comment by massimotisi** [comment]
Elle est encore dans mon repository: https://github.com/CACAO2016/CACAO2016/blob/master/PRIME_CACAO_2016/src/abstraction/equipe2/Achat.java

Si vous l'avez enlevez du votre, envoyez-moi une pull request
