### ISSUE TITLE
Lieutenants should watch this repository

### ISSUE THREAD

**Issue by massimotisi** [CACAO2016/CACAO2016#3]
All lieutenants (@jhtr, @AlexandreMARTY, @MarcSuteau, @SofianeSalort, @florianed, @lakac) should watch this repository (click on the button "Watch" and then "Watching") to receive notifications.

**Comment by florianed** [comment]
Bonjour, 
Pourquoi ai-je reçu ça?

> Date: Tue, 26 Apr 2016 04:59:20 -0700
> From: support@github.com
> To: floriane.dahman@hotmail.fr
> Subject: [GitHub] Your invitation to CACAO2016 has been canceled
> 
> Hi Floriane,
> 
> Your invitation to the CACAO2016 organization on GitHub has been canceled. Links to the invitation in previous emails will no longer work.
> 
> Thanks,
> The GitHub Team

Merci d'avance, 
Floriane

**Comment by massimotisi** [comment]
Dans un premier temps j'avais invité les lieutenants à faire partie de l'organisation git CACAO2016. Enfin je pense que ce n'est pas necessaire et j'ai annulé l'invitation.
