### ISSUE TITLE
First pull request from group 5

### ISSUE THREAD

**Issue by massimotisi** [CACAO2016/CACAO2016#9]
@florianed, can you send me a pull request from your repository?

**Comment by florianed** [comment]
Yes, I can. But I can't for the moment, I will do it this afternoon.

Floriane Dahman

**Comment by massimotisi** [comment]
Ok, and don't forget that before you will have to synchronize with the latest changes in my repository: 
1) fetch from... 2) merge 3) add to index 4) commit 5) push

**Comment by massimotisi** [comment]
Il faut que vous allez sur la page de votre repository "https://github.com/florianed/CACAO2016" et cliquez sur "New pull request"

**Comment by florianed** [comment]
Je viens de vous l'envoyer, l'avez vous accepté?

Floriane Dahman

**Comment by massimotisi** [comment]
Non mais on va continuer la discussion en commentaire à la pull request
